### ISSUE TITLE
output visualize problem

### ISSUE THREAD

**Issue by luohao123** [ruinmessi/ASFF#10]
I simply build yolov3 asff model like this:

```
model = build_model()
        a_t = torch.Tensor(a).unsqueeze(axis=0).to(device)
        out = model(a_t)[0]
```

Which out is a (48555, 85) shape tensor.

I think the first 4 dim is location, while 81 is the score. However, when i filtered out the locations with score bigger than 0.1 (which mostly reasonable), the result is bad:

![image](https://user-images.githubusercontent.com/49749220/69476189-ac874300-0e11-11ea-9700-fdf471143f11.png)

it gets more than 48000 results which apparently not the objects,

how to exactly get objects from these outputs?

**Comment by ruinmessi** [comment]
The 5th value is the iou score, then the last 80 are class scores, you may see the original yolo paper for more details.
