### ISSUE TITLE
demo for a single image

### ISSUE THREAD

**Issue by kaishijeng** [ruinmessi/ASFF#17]
@ruinmessi 

Any plan to have demo.py for a single image input?

Thanks,

**Comment by ruinmessi** [comment]
Not yet. And the current code has some visual tools in vis_utils.py.

**Comment by dreamhighchina** [comment]
看的太麻烦了，其实根本不需要什么eval.py 大多数都是自己的数据集，有自己的评判标准，你只要给个demo.py 就可以了，建议看看其他星多的开源代码
