### ISSUE TITLE
anchor guiding

### ISSUE THREAD

**Issue by hhaAndroid** [ruinmessi/ASFF#28]
First of all thank the author for the excellent code，especially the attempts of bof and ga。I looked at the code, I feel that your Guided Anchoring idea is not the same as the original paper, do you have time to explain the implementation ideas of this part of ga？ thank you

**Comment by ruinmessi** [comment]
Well, I didn't look at the official code of GA, and I just implement it on my own. I think the part of the WH prediction is not so different from the original paper. And if you have any suggestions, welcome to discuss below.

**Comment by hhaAndroid** [comment]
I read the ga thesis, he only used one channel to predict wh, that is n_anchor = 1, but I see you n_anchor = 4, is it necessary?

**Comment by ruinmessi** [comment]
Well, it's not necessary, but I think the guiding of both anchor-based and anchor-free branches would be more beneficial.

**Comment by hhaAndroid** [comment]
so the anchor prior setting is still important？I remember in the GA paper that the anchor prior is not sensitive，I am confused that you have set three anchor channel predictions, but the label calculations are all calculated using the predicted wh, it seems that the anchor base is not working。I think if you want to keep anchor base, then the first three channels should be calculated using anchor, and the last channel is ga

**Comment by hhaAndroid** [comment]
and I have a question about ga，since ga is used to predict anchor wh, this is actually very similar to anchor free, so why not directly predict bbox instead of predicting anchor. In this case, what is the significance of anchor base? Is there anything particularly significant? Using anchor free to directly predict wh, mAP is already very high

**Comment by ruinmessi** [comment]
Em...we use the low resolution of the input images on YOLO, so the pure anchor-free still suffers from the ambiguity of overlaps in ground-truth boxes during training.

**Comment by hhaAndroid** [comment]
You can take a look at this article that explains the problem！  Bridging the Gap Between Anchor-based and Anchor-free Detection via Adaptive Training Sample Selection https://arxiv.org/pdf/1912.02424.pdf

**Comment by ruinmessi** [comment]
Thanks, I have read it, a nice paper~
