### ISSUE TITLE
mismatch between the .pth you give and the ASSF model

### ISSUE THREAD

**Issue by dreamhighchina** [ruinmessi/ASFF#33]
RuntimeError:Error(s) in loading state_dict for YOLOv3:
 size mismatch for module_list.18.conv.weight:copying a param with shape 
torch.Size([1024,512,3,3]) from checkpoint,the shape in current model is torch.Size([256,512,3,3])

**Comment by ruinmessi** [comment]
I have verified all the models and no mismatch happened. Could you offer the details of which .pth file and your script?

**Comment by dreamhighchina** [comment]
Baseline.p t h




| |
钱文明
|
|
邮箱：18655197870@163.com
|

签名由 网易邮箱大师 定制

On 12/07/2019 20:09, ruinmessi wrote:

I have verified all the models and no mismatch happened. Could you offer the details of which .pth file and your script?

**Comment by ruinmessi** [comment]
remove the "--asff" and "--rfb" flag in your script

**Comment by luxdong** [comment]
> remove the "--asff" and "--rfb" flag in your script

it works! but i don't understand how it work?
