### ISSUE TITLE
vis model bug

### ISSUE THREAD

**Issue by DuZzzs** [ruinmessi/ASFF#40]
utils/cocoapi_evaluator.py line 186 will change `i` value. When using the vis（True） mode, the image obtained below does not correspond to the outputs above. It can be modified to the following:
```
for ind in range(bboxes.shape[0]):
       label = self.dataset.class_ids[int(cls[ind])]
       A = {"image_id": id_, "category_id": label, "bbox": bboxes[ind].numpy().tolist(),
       "score": scores[ind].numpy().item(), "segmentation": []} # COCO json format
       data_dict.append(A)
```

**Comment by ruinmessi** [comment]
Thanks a lot! I currently have no time and machine resource to update my code until next week, could you please raise a PR to fix this bug?

**Comment by ruinmessi** [comment]
fixed
