### ISSUE TITLE
evaluate

### ISSUE THREAD

**Issue by dodogoffy** [ruinmessi/ASFF#43]
Traceback (most recent call last):
  File "main.py", line 456, in <module>
    main()
  File "main.py", line 346, in main
    torch.save(model.module.state_dict(), os.path.join(args.save_dir,
  File "/home/lianguofei/workspace/ASFF/py35env/lib/python3.5/site-packages/torch/nn/modules/module.py", line 539, in __getattr__
    type(self).__name__, name))
AttributeError: 'YOLOv3' object has no attribute 'module'

你好，我想请问一下，这个具体要怎么解决？

**Comment by dodogoffy** [comment]
> Traceback (most recent call last):
> File "main.py", line 456, in
> main()
> File "main.py", line 346, in main
> torch.save(model.module.state_dict(), os.path.join(args.save_dir,
> File "/home/lianguofei/workspace/ASFF/py35env/lib/python3.5/site-packages/torch/nn/modules/module.py", line 539, in **getattr**
> type(self).**name**, name))
> AttributeError: 'YOLOv3' object has no attribute 'module'
> 
> 你好，我想请问一下，这个具体要怎么解决？

已解决。

**Comment by Wangweilai1** [comment]
@dodogoffy 训练过程中我遇到了同样的问题，你是怎么解决的？
