### ISSUE TITLE
error in eval.py

### ISSUE THREAD

**Issue by Guzaiwang** [ruinmessi/ASFF#48]
HI, when I run the eval.py, the mismatch error always occurs. 

In the terminal, the code is 
```
python -m torch.distributed.launch --nproc_per_node=2 --master_port=${RANDOM+10000} eval.py \
--cfg config/yolov3_baseline.cfg -d COCO --distributed --ngpu 2 \
--checkpoint weights/YOLOv3-ASFF_40.6.pth --half --asff --rfb -s 608
```

What confused me is which pretrained model should I choose. 

The errors are as follows:
`size mismatch for level_0_fusion.weight_level_0.conv.weight: copying a param with shape torch.Size([16, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([8, 512, 1, 1]).
        size mismatch for level_0_fusion.weight_level_0.batch_norm.weight: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([8]).
        size mismatch for level_0_fusion.weight_level_0.batch_norm.bias: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([8]).
        size mismatch for level_0_fusion.weight_level_0.batch_norm.running_mean: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([8]).
        size mismatch for level_0_fusion.weight_level_0.batch_norm.running_var: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([8]).
        size mismatch for level_0_fusion.weight_level_1.conv.weight: copying a param with shape torch.Size([16, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([8, 512, 1, 1]).
        size mismatch for level_0_fusion.weight_level_1.batch_norm.weight: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([8]).
        size mismatch for level_0_fusion.weight_level_1.batch_norm.bias: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([8]).
        size mismatch for level_0_fusion.weight_level_1.batch_norm.running_mean: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([8]).
        size mismatch for level_0_fusion.weight_level_1.batch_norm.running_var: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([8]).
        size mismatch for level_0_fusion.weight_level_2.conv.weight: copying a param with shape torch.Size([16, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([8, 512, 1, 1]).
        size mismatch for level_0_fusion.weight_level_2.batch_norm.weight: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([8]).
        size mismatch for level_0_fusion.weight_level_2.batch_norm.bias: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([8]).
        size mismatch for level_0_fusion.weight_level_2.batch_norm.running_mean: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([8]).
        size mismatch for level_0_fusion.weight_level_2.batch_norm.running_var: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([8]).
        size mismatch for level_0_fusion.weight_levels.weight: copying a param with shape torch.Size([3, 48, 1, 1]) from checkpoint, the shape in current model is torch.Size([3, 24, 1, 1]).
        size mismatch for level_1_fusion.weight_level_0.conv.weight: copying a param with shape torch.Size([16, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([8, 256, 1, 1]).`

Thanks for any help.

**Comment by ruinmessi** [comment]
YOLOv3-ASFF_40.6.pth doesn't use rfb module, so remove the '--rfb' flag

**Comment by Guzaiwang** [comment]
> YOLOv3-ASFF_40.6.pth doesn't use rfb module, so remove the '--rfb' flag

Thanks!!
