### ISSUE TITLE
Error occuring when run demo.py,  how can I solve it? THX

### ISSUE THREAD

**Issue by BucolicWind** [ruinmessi/ASFF#49]
python demo.py -i example/test.jpg --cfg config/yolov3_baseline.cfg -d COCO --checkpoint weights/YOLOv3-baseline_38.8.pth --half --rfb -s 608

Missing key(s) in state_dict: "module_list.19.Feature_adaption.rfb.branch_0.0.weight", "module_list.19.Feature_adaption.rfb.branch_0.0.bias",

**Comment by ruinmessi** [comment]
baseline doesn't use rfb module. Just remove "--rfb" flags
