### ISSUE TITLE
How about voc  07+12trainval in 07 test dataset map ？I only have 2080Ti*2, can I reproduce this value？

### ISSUE THREAD

**Issue by lovepan1** [ruinmessi/ASFF#6]

**Comment by ruinmessi** [comment]
This code currently supports VOC training, but for 2 GPUs, the low batchsize may downgrade the performance.

**Comment by ruinmessi** [comment]
For VOC, our experiments show that asff and rfb could not benefit a lot as on COCO. Both the baseline model and ASFF model can get about 84.0 mAP on 07 test. 
With two gpus, the low batchsize may downgrade the accuracy, you may turn-off the random resizing and use bigger batchsize.

**Comment by lovepan1** [comment]
OK. If  i get result, i will reply U ,thanks a lot.

**Comment by jwnirvana** [comment]
> OK. If i get result, i will reply U ,thanks a lot.

could you tell me whether you get result，thx

**Comment by lovepan1** [comment]
sorry, I'm traveling outside in these days，so，I didn't get results
