### ISSUE TITLE
About RetinaNet

### ISSUE THREAD

**Issue by zhuyu-cs** [ruinmessi/ASFF#78]
When I combine the ASFF module with the RetinaNet(behind the FPN module), the result is not good as the paper shows. Could you tell me the specific setting in your experiments?
I trained with the mmdetection, and the setting：batchsize16，lr0.01，12epochs.
         1.original RetinaNet's bbox map: 35.4%
         2.RetinaNet with ASFF_BN：35.1%
         3.RetinaNet with ASFF_GN: 35.7%

**Comment by TWDH** [comment]
Hi @zhuyu-cs , I have the same problem. I combine the RetinaNet with ASFF, also tried ResNet-FPN with ASFF. Both of them doesn't show better results. Have you solved this problem?
Thanks

**Comment by WangTianYuan** [comment]
@zhuyu-cs @TWDH  I have the same problem. Have you guys solved it?

**Comment by liuzhi111** [comment]
@WangTianYuan @TWDH @zhuyu-cs Have you solved this problem?
